---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
  name: {{ .Values.handle }}
spec:
  replicas: {{ .Values.deploymentconfig.replicas }}
  selector:
    name: {{ .Values.handle }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: {{ .Values.handle }}
      name: {{ .Values.handle }}
    spec:
      serviceAccountName: {{ .Values.handle }}
      containers:
      - args:
        - --http-address=:{{ .Values.ports.target }}
        - --https-address=
        - --openshift-service-account={{ .Values.handle }}
        - --upstream=http://localhost:{{ .Values.ports.targetConsole }}
        - --cookie-secret=bdna987REWQ1234
        image: openshift/oauth-proxy:latest
        imagePullPolicy: Always
        name: {{ .Values.handle }}-oauth-proxy
        ports:
        - containerPort: {{ .Values.ports.target }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: TEST_USER
          value: {{ .Values.deploymentconfig.env.user }}
        - name: APP_CONFIG
          value: {{ .Values.deploymentconfig.env.app }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: {{ .Values.handle }}-django
        image: ' '
        name: {{ include "app.name" . }}
        ports:
        - containerPort: {{ .Values.ports.targetConsole }}
        resources:
          limits:
            memory: {{ .Values.deploymentconfig.resources.limits.memory }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ include "app.name" . }}
      from:
        kind: ImageStreamTag
        name: {{ .Values.handle }}:latest
    type: ImageChange
  - type: ConfigChange
