{{- if .Values.cloudauth.secretEnable -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudauth.secretName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  osp_auth_url: {{ .Values.cloudauth.url | b64enc  }}
  osp_auth_project: {{ .Values.cloudauth.project | b64enc  }}
  osp_auth_username: {{ .Values.cloudauth.username | b64enc  }}
  osp_auth_password: {{ .Values.cloudauth.password | b64enc }}
{{- end }}

{{- if .Values.multiosp.secretEnable -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.multiosp.secretName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  clouds.yaml: {{ .Values.multiosp.clouds }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.handle }}-django
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  django-secret-key: {{ randAlphaNum 50 }}
