{{- if .Values.serviceaccount.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.{{ .Values.handle }}: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Values.handle }}"}}'
  creationTimestamp: null
  name: {{ .Values.handle }}
{{- end }}
