handle: labconsole

serviceaccount:
  enabled: true

route:
  enabled: true
  annotations: {}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  #useCertManager: ...
  domain: ''
  ref:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

service:
  name: web
  port: 8080
  annotations: {
    description: 'Exposes and load balances the application pods'
    }

buildconfig:
  annotations: {
    description: 'Defines how to build the application',
      template.alpha.openshift.io/wait-for-ready: 'true'
    }
  git:
    uri: https://github.com/yvarbanov/labconsole.git
    ref: ''
  env:
    pip: ''
  pyversion: 3.6
  namespace: openshift

deploymentconfig:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
  env:
    user: labconsole
    app: ''

ports:
  target: 5051
  targetConsole: 8080

cloudauth:
  secretEnable: true
  secretName: cloud-auth
  url: labconsole
  project: labconsole
  username: labconsole
  password: labconsole

multiosp: 
  secretEnable: true
  secretName: multi-osp
  path: /etc/labconsole/secrets
  clouds: >-
    labconsole_clouds_b64enc